const versionWords = new Set(["remix", "edit", "extended", "radio", "club", "vip", "mix"]);
const stopwords = new Set([...versionWords, "feat", "ft", "version", "album", "single", "original", "the", "a", "an", "of", "for", "and"]);
export const isrcPattern = /^[A-Z]{2}[A-Z0-9]{3}\d{7}$/;
export const uniqueValues = <T>(values: (T | null | undefined)[]) => [...new Set(values.filter((value): value is T => Boolean(value)))];
export const nameKey = (value: string) => value.toLocaleLowerCase().replace(/[^a-z0-9]+/g, "");
export const words = (value: string) => new Set((value.toLocaleLowerCase().match(/[a-z0-9]+/g) ?? []).filter((word) => !stopwords.has(word)));
export const marked = (title: string) => (title.toLocaleLowerCase().match(/[a-z]+/g) ?? []).some((word) => versionWords.has(word));
export function searchTitle(title: string): string { return title.replace(/\s*[([](?:feat|ft)\.?[^)\]]*[)\]]/gi, "").replace(/\s+/g, " ").trim(); }
export function versionPreference(title: string): number { const terms = new Set(title.toLocaleLowerCase().match(/[a-z]+/g) ?? []); return terms.has("extended") ? 2 : terms.has("radio") || terms.has("edit") ? 0 : 1; }
export interface MusicBrainzRelease { title?: string; status?: string; "release-group"?: { title?: string; "secondary-types"?: string[] } }
function similarity(left: string, right: string): number { const previous = Array.from({ length: right.length + 1 }, (_, index) => index); for (let row = 1; row <= left.length; row++) { let diagonal = previous[0]; previous[0] = row; for (let column = 1; column <= right.length; column++) { const above = previous[column]; previous[column] = left[row - 1] === right[column - 1] ? diagonal : Math.min(previous[column] + 1, previous[column - 1] + 1, diagonal + 1); diagonal = above; } } return left || right ? 1 - previous[right.length] / Math.max(left.length, right.length) : 0; }
export function releaseScore(release: MusicBrainzRelease, sourceAlbum: string): number { const group = release["release-group"] ?? {}; const source = nameKey(sourceAlbum); const titles = [nameKey(release.title ?? ""), nameKey(group.title ?? "")].filter(Boolean); let score = Math.max(0, ...titles.map((title) => similarity(source, title) * 100)); if (source && titles.includes(source)) score += 1000; if ((group["secondary-types"] ?? []).some((type) => type.toLocaleLowerCase() === "compilation") && !titles.includes(source)) score -= 30; if (release.status?.toLocaleLowerCase() === "official") score += 5; return score; }
