import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";

export interface StoredJob { id: string; importId?: string; kind: string; status: string; current: number; total: number; currentItem?: string; cancelRequested: boolean; error?: string }
const now = () => new Date().toISOString();

export class JobRepository {
  constructor(private readonly database: Database.Database) {}
  create(kind: string, importId?: string, total = 0): StoredJob { const id = randomUUID(); const at = now(); this.database.prepare("INSERT INTO jobs (id, import_id, kind, status, total, created_at, updated_at) VALUES (?, ?, ?, 'queued', ?, ?, ?)").run(id, importId ?? null, kind, total, at, at); return this.get(id); }
  get(id: string): StoredJob { const row = this.database.prepare("SELECT * FROM jobs WHERE id = ?").get(id) as Record<string, unknown> | undefined; if (!row) throw new Error(`unknown job: ${id}`); return { id: row.id as string, importId: row.import_id as string | undefined, kind: row.kind as string, status: row.status as string, current: row.current as number, total: row.total as number, currentItem: row.current_item as string | undefined, cancelRequested: Boolean(row.cancel_requested), error: row.error as string | undefined }; }
  list(limit = 50): StoredJob[] { return (this.database.prepare("SELECT id FROM jobs ORDER BY CASE status WHEN 'running' THEN 0 WHEN 'queued' THEN 1 ELSE 2 END, CASE WHEN status = 'queued' THEN created_at END ASC, updated_at DESC LIMIT ?").all(limit) as { id: string }[]).map((row) => this.get(row.id)); }
  requestCancel(id: string): void { this.database.prepare("UPDATE jobs SET cancel_requested = 1, status = CASE WHEN status = 'queued' THEN 'cancelled' ELSE status END, current_item = CASE WHEN status = 'running' THEN 'Cancellation requested' ELSE current_item END, updated_at = ? WHERE id = ?").run(now(), id); }
  update(id: string, values: Partial<Pick<StoredJob, "status" | "current" | "total" | "currentItem" | "error">>): void { const columns: Record<string, unknown> = { updated_at: now() }; if (values.status !== undefined) columns.status = values.status; if (values.current !== undefined) columns.current = values.current; if (values.total !== undefined) columns.total = values.total; if (values.currentItem !== undefined) columns.current_item = values.currentItem; if (values.error !== undefined) columns.error = values.error; const assignments = Object.keys(columns).map((key) => `${key} = ?`).join(", "); this.database.prepare(`UPDATE jobs SET ${assignments} WHERE id = ?`).run(...Object.values(columns), id); }
  claimNext(): StoredJob | undefined { return this.database.transaction(() => { const row = this.database.prepare("SELECT id FROM jobs WHERE status = 'queued' AND cancel_requested = 0 ORDER BY created_at, id LIMIT 1").get() as { id: string } | undefined; if (!row) return undefined; const claimed = this.database.prepare("UPDATE jobs SET status = 'running', updated_at = ? WHERE id = ? AND status = 'queued' AND cancel_requested = 0").run(now(), row.id); return claimed.changes === 1 ? this.get(row.id) : undefined; })(); }
}
