import type Database from "better-sqlite3";
import type { MusicBrainzResult } from "../domain/musicbrainz";
const now = () => new Date().toISOString();
const manualMethods = new Set(["manual_search", "manual_mbid", "imported_from_csv", "reused_manual"]);
export class ResolutionRepository { constructor(private readonly database: Database.Database) {}
  saveManual(entryId: number, result: MusicBrainzResult, method: string, validationStatus: "valid" | "warning", evidence: object = {}, selectedReleaseGroupId?: string): void { if (!manualMethods.has(method)) throw new Error(`invalid manual resolution method: ${method}`); const owner = this.database.prepare("SELECT import_id FROM playlist_entries WHERE id = ?").get(entryId) as { import_id: string } | undefined; if (!owner) throw new Error(`unknown playlist entry: ${entryId}`); const at = now(); const write = this.database.transaction(() => { this.database.prepare("UPDATE resolutions SET state = 'manually_resolved', method = ?, result_json = ?, evidence_json = ?, is_manual = 1, validation_status = ?, selected_release_group_id = ?, confirmed_at = ?, updated_at = ? WHERE entry_id = ?").run(method, JSON.stringify(result), JSON.stringify(evidence), validationStatus, selectedReleaseGroupId ?? null, at, at, entryId); this.invalidateDraftPlans(owner.import_id); this.database.prepare("UPDATE imports SET workflow_state = 'ready_to_plan', updated_at = ? WHERE id = ?").run(at, owner.import_id); }); write(); }
  clearManual(entryId: number): void { const result = this.database.prepare("UPDATE resolutions SET state = 'pending', method = NULL, result_json = '{}', evidence_json = '{}', is_manual = 0, validation_status = NULL, selected_release_group_id = NULL, confirmed_at = NULL, updated_at = ? WHERE entry_id = ?").run(now(), entryId); if (result.changes !== 1) throw new Error(`unknown playlist entry: ${entryId}`); }
  setVariousArtistsOverride(entryId: number, allowed: boolean): void { const row = this.database.prepare("SELECT e.import_id, r.evidence_json FROM playlist_entries e JOIN resolutions r ON r.entry_id = e.id WHERE e.id = ?").get(entryId) as { import_id: string; evidence_json: string } | undefined; if (!row) throw new Error(`unknown playlist entry: ${entryId}`); const evidence = JSON.parse(row.evidence_json || "{}") as Record<string, unknown>; if (allowed) evidence.allow_various_artists_release = true; else delete evidence.allow_various_artists_release; const at = now(); this.database.transaction(() => { this.database.prepare("UPDATE resolutions SET evidence_json = ?, updated_at = ? WHERE entry_id = ?").run(JSON.stringify(evidence), at, entryId); this.invalidateDraftPlans(row.import_id); this.database.prepare("UPDATE imports SET workflow_state = 'ready_to_plan', updated_at = ? WHERE id = ?").run(at, row.import_id); })(); }
  private invalidateDraftPlans(importId: string): void { this.database.prepare("UPDATE lidarr_plans SET status = 'superseded' WHERE import_id = ? AND status = 'draft'").run(importId); }
}
