from typing import Protocol

from ...domain.models import AcquiredTrack, PlaylistInfo, SourceTrack


class MusicSource(Protocol):
    name: str

    def login(self) -> None: ...
    def list_playlists(self) -> list[PlaylistInfo]: ...
    def get_playlist(self, playlist_id_or_url: str) -> PlaylistInfo: ...
    def get_tracks(self, playlist: PlaylistInfo) -> list[SourceTrack]: ...
    def get_entries(self, playlist: PlaylistInfo) -> list[AcquiredTrack]: ...
